LOCAL_PATH := $(call my-dir)
_IMPORT_PREFIX := $(LOCAL_PATH)/../../..

include $(CLEAR_VARS)
LOCAL_MODULE := SDL2-static
LOCAL_SRC_FILES := $(_IMPORT_PREFIX)/lib/libSDL2.a
LOCAL_CPP_FEATURES := rtti exceptions
# COMPATIBLE_INTERFACE_BOOL SDL2_SHARED
# COMPATIBLE_INTERFACE_STRING SDL_VERSION
LOCAL_EXPORT_C_INCLUDES := ${_IMPORT_PREFIX}/include\
${_IMPORT_PREFIX}/include/SDL2
LOCAL_STATIC_LIBRARIES := sdl-build-options
LOCAL_EXPORT_LDLIBS := -lm -lOpenSLES -ldl -llog -landroid -lGLESv1_CM -lGLESv2
# INTERFACE_SDL2_SHARED FALSE
# INTERFACE_SDL_VERSION SDL2
LOCAL_HAS_CPP := true
include $(PREBUILT_STATIC_LIBRARY)

