name: 构建Android

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'
        required: true

permissions:
  contents: write

jobs:

  windows:
    runs-on: ubuntu-latest
    steps:
    - name: 配置NDK r21e
      uses: nttld/setup-ndk@v1
      id: setup_ndk
      with:
        ndk-version: r21e

    - name: 安装环境
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install ninja-build pkg-config
        sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libasound2-dev libxinerama-dev libxi-dev qtbase5-dev qtbase5-dev-tools
        sudo apt-get install -y clang

    - name: 签出源码
      uses: actions/checkout@v3

    - name: SDL2
      run: |
        cd 3rdparty/sdl2
        cmake -S . -B build_arm64 \
            -DANDROID_PLATFORM=android-24 \
            -DANDROID_ABI=arm64-v8a \
            -DCMAKE_INSTALL_PREFIX=~/sdl2-arm64 \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup_ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
            -DSDL_SHARED=ON -DSDL_STATIC=ON -DSDL_STATIC_PIC=ON -DSDL_TEST=ON \
            -DSDL2_DISABLE_SDL2MAIN=OFF -DSDL2_DISABLE_INSTALL=OFF \
            -DCMAKE_INSTALL_INCLUDEDIR=include -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release \
            -DSDL_VENDOR_INFO="Github Workflow" \
            -GNinja
        cmake --build build_arm64 --config Release --parallel --verbose
        cmake --install build_arm64 --config Release

    - name: 编译项目
      env:
        OVERRIDE_CC: clang
        OVERRIDE_CXX: clang++
        ARCHOPTS: -U_FORTIFY_SOURCE
        SUBTARGET: tiny
        SDL_INSTALL_ROOT: ~/sdl2-arm64
      run: |
        make -j9 android-arm64
        ls

    - name: 上传资源
      uses: actions/upload-artifact@v3
      with:
        name: neogeo-windows
        path:  |
          ./build/release/x64/Release/neogeo/**/*

  publish:
    runs-on: ubuntu-latest
    needs: [ windows ]
    steps:
    - name: 下载资源
      uses: actions/download-artifact@v3
      with:
        name: neogeo-windows
        path: neogeo-windows/

    - name: 打包资源
      run: |
        cd neogeo-windows/ && tar cvfz ../neogeo_${{ github.event.inputs.tag_name }}.tgz ./ && cd -

    - name: 发布版本
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.tag_name }}
        name: server-v${{ github.event.inputs.tag_name }}
        body: v${{ github.event.inputs.tag_name }} 版本发布
        draft: false
        prerelease: false
        files: |
          neogeo_${{ github.event.inputs.tag_name }}.tgz
